spring.application.name=pictweet_java_backend
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=postgres
spring.datasource.password=
spring.flyway.baselineOnMigrate=true